// ignore file coverage

import type {
  Base58,
  Hash,
  KeyScope,
  Keyring,
  SyncState,
  UnixTimestamp,
  UserWithSecrets,
} from '@localfirst/crdx'
import type {
  Device,
  DeviceWithSecrets,
  FirstUseDevice,
  FirstUseDeviceWithSecrets,
} from 'device/index.js'
import type {
  DeviceInvitationClaim,
  MemberInvitationClaim,
  ProofOfInvitationV2,
} from 'invitation/index.js'
import type { ServerWithSecrets } from 'server/index.js'
import type { Member, Team } from 'team/index.js'
import type { ConnectionErrorPayload } from './errors.js'
import type { ConnectionMessage } from './message.js'
import type { InvitationAcceptanceValidationResult } from './validateInvitationAcceptance.js'

export type ConnectionEvents = {
  /** state change in the connection */
  change: (summary: string) => void

  /** message received from peer */
  message: (message: unknown) => void

  /** Our peer has detected an error and reported it to us, e.g. we tried to join with an invalid invitation. */
  remoteError: (error: ConnectionErrorPayload) => void

  /** We've detected an error locally, e.g. a peer tries to join with an invalid invitation. */
  localError: (error: ConnectionErrorPayload) => void

  /** We're connected to a peer and have been mutually authenticated. */
  connected: () => void

  /**
   * We've successfully joined a team using an invitation. This event provides the team graph and
   * the user's info (including keys). (When we're joining as a new device for an existing user,
   * this is how we get the user's keys.) This event gives the application a chance to persist the
   * team graph and the user's info. The session key has already been committed, so listeners may
   * immediately call `Connection.send`. This event follows `connectionSecured`.
   */
  joined: ({ team, user }: { team: Team; user: UserWithSecrets; teamKeyring: Keyring }) => void

  /** The team graph has been updated. This event gives the application a chance to persist the changes. */
  updated: (head: string[]) => void

  /** The auth connection disconnects from a peer after entering an error state. */
  disconnected: (event: ConnectionMessage) => void

  sync: ({ team, user }: { team: Team; user: UserWithSecrets }) => void

  /**
   * Identities have been validated and the session key is committed. Listeners may immediately use
   * the encrypted-channel API.
   */
  connectionSecured: () => void
}

// IDENTITY CLAIMS

export type MemberIdentityClaim = {
  // I'm already a member, I just send my deviceId
  deviceId: string
}

export type InviteeMemberIdentityClaim = MemberInvitationClaim & {
  // I'm a new user and I have an invitation
  proofOfInvitation: ProofOfInvitationV2
}

export type InviteeDeviceIdentityClaim = DeviceInvitationClaim & {
  // I'm a new device for an existing user and I have an invitation
  proofOfInvitation: ProofOfInvitationV2
}

export type InviteeIdentityClaim = InviteeMemberIdentityClaim | InviteeDeviceIdentityClaim

export type IdentityClaim = MemberIdentityClaim | InviteeIdentityClaim

// CONTEXT

export type MemberContext = {
  user: UserWithSecrets
  device: DeviceWithSecrets
  team: Team
}

export type InviteeMemberContext = {
  user: UserWithSecrets
  device: DeviceWithSecrets
  invitationSeed: string

  /** Full immutable team root obtained with the invitation; never a truncated discovery ID. */
  expectedTeamId: Base58
}

export type InviteeDeviceContext = {
  userName: string
  device: FirstUseDeviceWithSecrets
  invitationSeed: string

  /** Full immutable team root obtained with the invitation; never a truncated discovery ID. */
  expectedTeamId: Base58
}

export type InviteeContext = InviteeMemberContext | InviteeDeviceContext

export type ServerContext = {
  server: ServerWithSecrets
  team: Team
}

export type Context = MemberContext | InviteeContext | ServerContext

export type Challenge = KeyScope & {
  nonce: Base58
  timestamp: UnixTimestamp
}

export type ConnectionContext = {
  device: DeviceWithSecrets | FirstUseDeviceWithSecrets

  /** Nonce we sent with REQUEST_IDENTITY, to which an invitee proof must be bound. */
  acceptorNonce: Base58

  /** Nonce generated by this peer for any invitation claim it sends. */
  inviteeNonce: Base58

  ourIdentityClaim?: IdentityClaim
  theirIdentityClaim?: IdentityClaim
  invitationAcceptanceResult?: InvitationAcceptanceValidationResult

  challenge?: Challenge

  theirDevice?: Device | FirstUseDevice
  peer?: Member

  seed?: Uint8Array
  theirEncryptedSeed?: Uint8Array
  sessionKey?: Uint8Array

  theirHead?: Hash
  syncState?: SyncState

  error?: ErrorPayload
} & Partial<InviteeDeviceContext> &
  Partial<InviteeMemberContext> &
  Partial<ServerContext> &
  Partial<MemberContext>

export type ErrorPayload = {
  message: string
  details?: any
}

// TYPE GUARDS

// initial context

type C = Context | ConnectionContext

export const isMemberContext = (c: C): c is MemberContext => {
  return 'team' in c && c.team !== undefined
}

export const isInviteeContext = (c: C): c is InviteeContext => {
  return 'invitationSeed' in c && c.invitationSeed !== undefined
}

export const isInviteeMemberContext = (c: C): c is InviteeMemberContext => {
  return isInviteeContext(c) && 'user' in c && c.user !== undefined
}

export const isInviteeDeviceContext = (c: C): c is InviteeDeviceContext => {
  return isInviteeContext(c) && !isInviteeMemberContext(c)
}

export const isServerContext = (c: C): c is ServerContext => {
  return 'server' in c && c.server !== undefined
}

// identity claim

export const isMemberClaim = (claim: IdentityClaim): claim is MemberIdentityClaim => {
  return 'deviceId' in claim && claim.deviceId !== undefined
}

export const isInviteeMemberClaim = (claim: IdentityClaim): claim is InviteeMemberIdentityClaim => {
  return isInviteeClaim(claim) && claim.invitationKind === 'member'
}

export const isInviteeDeviceClaim = (claim: IdentityClaim): claim is InviteeDeviceIdentityClaim => {
  return isInviteeClaim(claim) && claim.invitationKind === 'device'
}

export const isInviteeClaim = (claim: IdentityClaim): claim is InviteeIdentityClaim => {
  return 'proofOfInvitation' in claim && claim.proofOfInvitation !== undefined
}
